### ISSUE TITLE
Running multiple blue-green swarms

### ISSUE THREAD

**Issue by olliejm** [botleg/blue-green#3]
Just a question here. Let's say I have 2+ services which I want to run using this blue-green deployment image.

Is it as simple as just repeating the steps to set up the initial service? I.e. create new master and slave docker machines for the new service? And would they use the same consul service or require their own?

I have managed to get a setup working by doing that (creating new master and slave vms using the same consul service), but I'm unsure if it is the correct way to go about it. 

I noticed that the old swarm nodes now have the same swarm name as the new swarm when running `docker-machine ls`. I also tried to build a new image within the old swarm, and it kept delegating to the slave node of the new swarm to build (I may have been doing something else wrong there though).

Thanks for any help

**Comment by hanzeljesheen** [comment]
You can use the same consul and even the same stack. You'd have to change some of the names, which is straight forward. If you can share the commands and `docker-compose` file, I can help you better.

**Comment by olliejm** [comment]
```yaml
version: '3'

services:
  bg:
    image: hanzel/blue-green
    container_name: bg-service2
    ports:
      - "80:80"
      - "8080:8080"
    environment:
      - constraint:node==service2-master
      - CONSUL_URL=10.0.1.43:8500
      - BLUE_NAME=blue
      - GREEN_NAME=green
      - LIVE=blue
    depends_on:
      - green
      - blue
    networks:
      - blue-green

  blue:
    image: service2image:1
    ports:
      - "80"
    environment:
      - SERVICE_80_NAME=blue
    networks:
      - blue-green

  green:
    image: service2image:2
    ports:
      - "80"
    environment:
      - SERVICE_80_NAME=green
    networks:
      - blue-green

networks:
  blue-green:
    driver: overlay
```

So that would be my `docker-compose.yml` for `service2`, and the file for `service1` is exactly the same (with different names). I am using one consul image for both, but otherwise have repeated the commands  for both `service1` and `service2`, except again, using different names.

Thanks.
